// Code generated by hertz generator.

package main

import (
	"context"
	handler "douyin_proj/biz/handler"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// 注册定义路由
// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/hertz/:version/*action", func(ctx context.Context, c *app.RequestContext) {
		version := c.Param("version")
		action := c.Param("action")
		message := version + "is" + action
		c.String(consts.StatusOK, message)
	})
	// your code ...
	douyin := r.Group("/douyin")
	{
		// 视频feed流
		r.GET("/feed", handler.Feed)
		// 用户
		userGroup := douyin.Group("/user")
		{
			userGroup.POST("/login", handler.UserLogin)
			userGroup.POST("/register", handler.UserRegister)
			userGroup.GET("/:id", handler.GetUser)
		}
		//	视频投稿和发布
		publishGroup := douyin.Group("/publish")
		{
			publishGroup.POST("/action", handler.Publish)  // 视频发布
			publishGroup.GET("/list", handler.PublishList) // 发布列表
		}
	}

}
